server:
  servlet:
    #访问资源所用名
    context-path: /vote
  #访问资源所用端口号
  port: 8080


#映射静态资源
spring:
  mvc:
    static-path-pattern: /**
  resources: #提供所支持的静态资源访问文件夹
    static-locations: classpath:/templates/,classpath:/META-NF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/upload
  #提供对thymeleaf模板的视图解析器
  thymeleaf:
    encoding: utf-8
    #开发时关闭缓存，不然无法看到实时页面(需重启)
    cache: false
    #prefix: / #classpath:/templates/ #(默认)
    #suffix: .html #(默认)
  #spring
  #数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///bdqn?serverTimezone=GMT
    #username: root
    #password: root
    username: root
    password: root
#mybatis配置
mybatis:
  type-aliases-package: cn.bdqn.pojo
  configuration:
    auto-mapping-behavior: full
    use-generated-keys: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
pagehelper:
  helperDialect: mysql
  reasonable: true
  pageSizeZero: true